# Generated by Django 4.0.6 on 2022-07-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_caliber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_name', models.CharField(max_length=25, unique=True)),
                ('gun_num', models.CharField(max_length=25)),
                ('gun_body', models.TextField()),
                ('gun_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=25, null=True, unique=True)),
                ('authorr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caliber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.caliber')),
            ],
        ),
    ]
