# Generated by Django 2.2.24 on 2022-08-16 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gun',
            old_name='authorr',
            new_name='author',
        ),
        migrations.AddField(
            model_name='gun',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='caliber',
            name='gun_caliber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='caliber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='gun_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='gun',
            name='gun_num',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Komentarz')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gun_comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Gun')),
            ],
        ),
    ]
